apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
      kompose.version: 1.20.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: static1-backend
    name: static1-backend
    namespace: scrape
  spec:
    ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    selector:
      io.kompose.service: static1-backend
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
      kompose.version: 1.20.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: static1-backend
    name: static1-backend
    namespace: scrape
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
          kompose.version: 1.20.0 ()
        creationTimestamp: null
        labels:
          io.kompose.service: static1-backend
      spec:
        containers:
        - env:
          - name: PGSQL_DATABASE
            value: scrape_static1
          - name: PGSQL_HOST
            valueFrom:
              secretKeyRef:
                name: pgsql
                key: PGSQL_HOST
          - name: PGSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgsql
                key: PGSQL_PASSWORD
          - name: PGSQL_PORT
            valueFrom:
              secretKeyRef:
                name: pgsql
                key: PGSQL_PORT
          - name: PGSQL_USER
            valueFrom:
              secretKeyRef:
                name: pgsql
                key: PGSQL_USER
          image: germey/scrape-static1-backend:${TAG}
          name: scrape-static1-backend
          ports:
          - containerPort: 8000
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-static1
  namespace: scrape
spec:
  rules:
    - host: static1.scrape.cuiqingcai.com
      http:
        paths:
          - backend:
              serviceName: static1-frontend
              servicePort: 80
            path: /