version: '3'
services:
  captcha6-backend:
    container_name: 'scrape-captcha6-backend'
    restart: always
    build: ./backend
    image: 'germey/scrape-captcha6-backend:${BUILD_NUMBER}'
    ports:
      - '8000:8000'
    environment:
      CAPTCHA_TYPE: 'NINE'
  captcha6-frontend:
    container_name: 'scrape-captcha6-frontend'
    restart: always
    build: ./frontend
    image: 'germey/scrape-captcha6-frontend:${BUILD_NUMBER}'
    depends_on:
      - 'captcha6-backend'
    ports:
      - '8083:80'