version: '3'
services:
  dynamic5-backend:
    container_name: 'scrape-dynamic5-backend'
    restart: always
    build: ./backend
    image: 'germey/scrape-dynamic5-backend:${BUILD_NUMBER}'
    ports:
      - '8000:8000'
    environment:
      PGSQL_HOST:
      PGSQL_PORT:
      PGSQL_USER:
      PGSQL_PASSWORD:
      PGSQL_DATABASE: 'scrape_news'
  dynamic5-frontend:
    container_name: 'scrape-dynamic5-frontend'
    restart: always
    build: ./frontend
    image: 'germey/scrape-dynamic5-frontend:${BUILD_NUMBER}'
    depends_on:
      - 'dynamic5-backend'
    ports:
      - '8083:80'
  dynamic5-spider:
    container_name: 'scrape-dynamic5-spider'
    restart: always
    build: ./spider
    image: 'germey/scrape-dynamic5-spider:${BUILD_NUMBER}'
    environment:
      PGSQL_HOST:
      PGSQL_PORT:
      PGSQL_USER:
      PGSQL_PASSWORD:
      PGSQL_DATABASE: 'scrape_news'