version: '3'
services:
  login1-frontend:
    container_name: 'scrape-login1-frontend'
    restart: always
    build: ./frontend
    image: 'germey/scrape-login1-frontend:${BUILD_NUMBER}'
    ports:
      - '8080:80'