version: '3'
services:
  captcha5-backend:
    container_name: 'scrape-captcha5-backend'
    restart: always
    build: ./backend
    image: 'germey/scrape-captcha5-backend:${BUILD_NUMBER}'
    ports:
      - '8000:8000'
    environment:
      CAPTCHA_TYPE: 'SPACE'
  captcha5-frontend:
    container_name: 'scrape-captcha5-frontend'
    restart: always
    build: ./frontend
    image: 'germey/scrape-captcha5-frontend:${BUILD_NUMBER}'
    depends_on:
      - 'captcha5-backend'
    ports:
      - '8083:80'