version: '3'
services:
  captcha4-backend:
    container_name: 'scrape-captcha4-backend'
    restart: always
    build: ./backend
    image: 'germey/scrape-captcha4-backend:${BUILD_NUMBER}'
    ports:
      - '8000:8000'
    environment:
      CAPTCHA_TYPE: 'PHRASE'
  captcha4-frontend:
    container_name: 'scrape-captcha4-frontend'
    restart: always
    build: ./frontend
    image: 'germey/scrape-captcha4-frontend:${BUILD_NUMBER}'
    depends_on:
      - 'captcha4-backend'
    ports:
      - '8083:80'