version: '3'
services:
  captcha1-backend:
    container_name: 'scrape-captcha1-backend'
    restart: always
    build: ./backend
    image: 'germey/scrape-captcha1-backend:${BUILD_NUMBER}'
    ports:
      - '8000:8000'
    environment:
      CAPTCHA_TYPE: 'SLIDE'
  captcha1-frontend:
    container_name: 'scrape-captcha1-frontend'
    restart: always
    build: ./frontend
    image: 'germey/scrape-captcha1-frontend:${BUILD_NUMBER}'
    depends_on:
      - 'captcha1-backend'
    ports:
      - '8083:80'